### ISSUE TITLE
2 Bugs Ig, one major one minor. (Nailgun Animation & V2 Healthbar Crashing)

### ISSUE THREAD

**Issue by StRyKeRxT** [absolutelyaya/ultracraft#106]
1: When I swap from my nailgun to another hotbar slot while firing, the firing animation still happens. Minor, but it would be cool to fix.
2: I spawned the V2 boss fight in my Cybergrind map, and it kept flying off the map, so I went to another map to do the fight. I come back to the Cybergrind map, and it crashes the game. I think it has something to do with V2 still doing the leaving animation from falling into the void, and the healthbar was a variable that the game depended on, because it came out with this error: (image attached)

**Comment by absolutelyaya** [comment]
while there's no attached image, I found the crash and fixed it interally; it'll be part of the next update
