### ISSUE TITLE
Slamming can destroy dropped items

### ISSUE THREAD

**Issue by delishoes** [absolutelyaya/ultracraft#115]
For some reason, air slams can destroy (or kill) dropped items similiar to how cacti does it

**Comment by absolutelyaya** [comment]
should've been fixed in 2.1.1- does it still happen there ?

**Comment by delishoes** [comment]
No, it does not happen anymore. This issue probably wasn't even necessary because of the hotfix releasing like 10 minutes after i made it lmao
