### ISSUE TITLE
Crash on creating new world: Missing sound file

### ISSUE THREAD

**Issue by ChromaPIE** [absolutelyaya/ultracraft#117]
The sound `ultracraft:music.limbo.calm` referred in `data\ultracraft\worldgen\biome\limbo.json` is not present, causing the crash.

**Comment by ChromaPIE** [comment]
More issue came out. https://mclo.gs/H4On8Ld

**Comment by absolutelyaya** [comment]
that by itself shouldn't cause a crash; can you send a full crash report ?

**Comment by ChromaPIE** [comment]
I did more tests later. There's another mod causing problems which can actually crash the game so I guess for Ultracraft it's only this small issue.
