### ISSUE TITLE
Cannot load "straight to hell" level

### ISSUE THREAD

**Issue by Problemreported** [absolutelyaya/ultracraft#119]
The level "Straight to hell" cant load and always says "failed to initiate level structure."

![2024-04-13_12 09 29](https://github.com/absolutelyaya/ultracraft/assets/115743004/dcce51f3-fb73-43e6-9a11-0352b4826687)

I am using a elevator panel to access the levels

**Comment by absolutelyaya** [comment]
could you post a log as well ? I can't do much with this alone unfortunately

**Comment by Problemreported** [comment]
While I was attempting to record an example and then put a log too, but for some odd reason it decided to work..
Idk
