### ISSUE TITLE
Projectile Boosting your own Arrows Heals you

### ISSUE THREAD

**Issue by SCAbruh** [absolutelyaya/ultracraft#122]
Attempting to Projectile Boost arrows shot from your own bow actually counts as a parry and fully heals you.

https://github.com/absolutelyaya/ultracraft/assets/35113327/8246e44b-e550-4338-af73-788b22b72886

**Comment by absolutelyaya** [comment]
I mean technically that is a parry; maybe I should change it so that you can't parry your own projectiles after the projectile boost window
welp, in any case, you're right it should at least not heal you
