### ISSUE TITLE
Crash when putting ultracraft:sky_block{type: x} into the door listener

### ISSUE THREAD

**Issue by SurelyNotClover** [absolutelyaya/ultracraft#123]
[Crash Log.txt](https://github.com/absolutelyaya/ultracraft/files/15223321/Crash.Log.txt)

To be exact the command went like this: /edit attribute listener closedBlock "ultracraft:sky_block{\"type: night\"}"

**Comment by absolutelyaya** [comment]
Block States and NBT aren't currently supported; make sure to only put in the identifier and it should work
At least the crash will be fixed in the next update
