### ISSUE TITLE
Scoreboard criteria "minecraft.custom:minecraft.sneak_time" doesn't apply in any way during HiVel

### ISSUE THREAD

**Issue by vred1** [absolutelyaya/ultracraft#130]
1) Create a scoreboard with custom criteria "minecraft.custom:minecraft.sneak_time"
2) sneak with HiVel mode (even with custom keybind)
3) scoreboard doesn't increase
this breaks my datapack 😔

**Comment by absolutelyaya** [comment]
since you can't sneak in hivel, that's intended behavior
