### ISSUE TITLE
Level Skulls Sending to the Shadow Realm

### ISSUE THREAD

**Issue by felonymisdemeanor** [absolutelyaya/ultracraft#131]
Upon grabbing a skull within a level, switching to the machinesword (or variants) in the mainhaind will result in the skull itself being deleted from the player's inventory.
(GIF link if it hasn't been deleted from ezgif's [servers](https://s1.ezgif.com/tmp/ezgif-1-4449729097.gif) hopefully.)

**Comment by absolutelyaya** [comment]
if you're using better combat, then that's because the machine sword is a two handed weapon, making the offhand invisible. The Skull should return when putting the sword away
If that's not it, feel free to re-open the issue ofc

**Comment by absolutelyaya** [comment]
pretty sure this was fixed in [v2.1.3](https://github.com/absolutelyaya/ultracraft/releases/tag/1.20.1-v2.1.3), dunno why I didn't close the issue
