### ISSUE TITLE
a bunch of problems

### ISSUE THREAD

**Issue by bsticks4** [absolutelyaya/ultracraft#134]
Main problem is that terminals don't have the hud and dont even work,the  second one is the OST not playing and the third is skyblocks not functioning correctly(they are transparent and more like an x-ray through blocks), also skull doors dont work

**Comment by absolutelyaya** [comment]
remove iris or any other rendering mods like it. that'll fix skyblocks and terminals
as for the music, make sure music (top left slider) isn't at 0% volume in your sound settings

**Comment by bsticks4** [comment]
alright thanks, as for the music I had an old version of the mod so i just had to update it
