### ISSUE TITLE
Issues with the mod and fabric's loader

### ISSUE THREAD

**Issue by TheTroubledGamer** [absolutelyaya/ultracraft#135]
I just installed the mod and fabric api but it says it needs any version of fabric??? and it's on fabric already below is the error message and image
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Ultracraft' (ultracraft) 1.20.1-2.1.pride2 requires any version of fabric, which is missing!
	 - Mod 'Goop Technology' (goop) 1.20.x-0.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
https://github.com/absolutelyaya/ultracraft/assets/174516306/4a35ce01-c152-42fa-88d8-a180ec1a134b

**Comment by TheTroubledGamer** [comment]
and what is goop technology?

**Comment by absolutelyaya** [comment]
you need to install fabric api
Goop is what adds the blood splatter particle effects; I moved it into its own mod so others can use the particles as well

**Comment by TheTroubledGamer** [comment]
but I already have fabric api istalled for it
