### ISSUE TITLE
Attractor Nailgun Does not shoot magnets sometimes and does not recharge magnets in newest update

### ISSUE THREAD

**Issue by ContagiousPow** [absolutelyaya/ultracraft#136]
in the Clair de Lune update, the attractor nailgun does not shoot magnets sometimes, and can stop recharging, making it useless.

**Comment by absolutelyaya** [comment]
are there specific circumstances under which this happens ? I couldn't recreate the issue myself (I've only tested in singleplayer so far tho)

**Comment by ContagiousPow** [comment]
this was in singleplayer, on my older world, fighting (specifically speedrunning) v2. I believe after exiting the level and reopening it, the nailgun would not work
