### ISSUE TITLE
Sky blocks are all the sunny day variant in the newest update

### ISSUE THREAD

**Issue by ContagiousPow** [absolutelyaya/ultracraft#137]
In the Clair de Lune update, despite there being 2 new sky block types in the creative inventory, all display the "sunny day" variant, instead of their proper texture

**Comment by absolutelyaya** [comment]
are you using any other rendering mods ? the blocks and items look fine to me

**Comment by ContagiousPow** [comment]
I was using sodium and iris, that may be the issue

**Comment by absolutelyaya** [comment]
removing iris will most likely fix it

**Comment by ContagiousPow** [comment]
It was something to do with other mods, running ultracraft by itself fixed it, though i havent figured out what mod did it yet

**Comment by ContagiousPow** [comment]
(it was iris' fault i forgot to turn it off)
