### ISSUE TITLE
The supporter patterns do not appear

### ISSUE THREAD

**Issue by Xaicracker** [absolutelyaya/ultracraft#139]
Hi yaya, the supporter patterns are not appearing, Tomato and I wanted to use them but they're not there, 
![image_2024-08-03_192217713](https://github.com/user-attachments/assets/09746c76-6d71-4866-a2cd-076499179207)
I'm not used to submitting issues so sorry if this vague

**Comment by absolutelyaya** [comment]
Do you have the `Disable Flashy VFX` Client Setting enabled ?
If so, turn it off and they should appear again
