### ISSUE TITLE
Swordsmachine missing their shotguns? (Visual Error)

### ISSUE THREAD

**Issue by AshenWulf** [absolutelyaya/ultracraft#145]
I noticed while playing 0-2 during the first swordsmachine fight, that any swordsmachine model is missing their shotgun (before reaching half health). I tested this in creative as well, all swordsmachine entities are missing their guns, and it seems to be some sort of texture or UV mapping issue upon closer inspection. I have no idea if this has been a thing, but I'm playing with mods that should not affect this.

**Comment by absolutelyaya** [comment]
looks fine to me
![image](https://github.com/user-attachments/assets/a83fad49-7140-4f6a-83d2-99af0bcf03ca)

**Comment by AshenWulf** [comment]
Weird... I'll look on my end and see what could be wrong, I'll close this if its some compatibility issue with what I'm using

**Comment by AshenWulf** [comment]
It was compatibility, for some reason the Azurelib mod makes the shotgun texture bug out.. disregard
