### ISSUE TITLE
Skyblocks dont render when using shaders

### ISSUE THREAD

**Issue by Dial-t0ne** [absolutelyaya/ultracraft#146]
When using shaders (Im using specifically BSL - Original, Havent tested any other shaders.) The skyblock skybox doesnt render. it turns all the blocks under it transperent.
![2024-09-20_23 26 21](https://github.com/user-attachments/assets/5270efee-ade6-421a-9430-15f5be536cee)

**Comment by absolutelyaya** [comment]
Sorry, but Shaders won't be fully supported. Best I can do is prevent the game crashing when using them unfortunately
Removing rendering mods like Iris will resolve all visual issues in most cases
