### ISSUE TITLE
Piercer Charged Shots can't ricoshot off of Coins

### ISSUE THREAD

**Issue by AngelTechnic** [absolutelyaya/ultracraft#65]
And specifically, ONLY Piercer charged shots. All revolvers' primary shots work fine, Sharpshooter spin shot works fine, it's only the Piercer that suffers from this.

**Comment by Liskanyme** [comment]
either I misunderstood something, or it's not true, because everything works in fashion, I checked

**Comment by absolutelyaya** [comment]
It is bugged. It doesn't ricochet if there is a target (Living Entity or other Coins), but if there isn't one, the random fake hitscans still display
