### ISSUE TITLE
 small shotgun problems

### ISSUE THREAD

**Issue by Liskanyme** [absolutelyaya/ultracraft#69]
firstly, the player transfers too much momentum to the shot, because of this, using slam storage and shooting down the shot will fly up, I don’t think it should be like that, secondly, reloading a pump-action shotgun, although faster than usual, is still slow, in the original, the use of alt fire and reload have almost the same speed, it's not that a mistake, it's just not a match with the original

and yes, since I have no idea how to use github, there will be no tags, they converted to Islam and will not accept Christianity again

**Comment by Liskanyme** [comment]
about Islam and Christianity, this is a meme that most likely is not in non-Russian-speaking communities

**Comment by absolutelyaya** [comment]
I think the cooldown is fine considering how OP shotguns are regardless.

**Comment by Liskanyme** [comment]
I'm not saying that this is a mistake, I just mean that in the original it's a little different
