### ISSUE TITLE
Mod compatibility bug with JourneyMap waypoints

### ISSUE THREAD

**Issue by V1E4S** [absolutelyaya/ultracraft#70]
Not sure how the GUI is built together behind the scenes, but the JourneyMap mod uses a waypoint system, and its display breaks the UltraCraft HUD when any waypoints are being rendered.

I took a video to showcase what exactly happens. Just thought I'd let you know about this.
https://github.com/absolutelyaya/ultracraft/assets/41254732/72640519-66e8-488d-b4c8-1692b39bbf5c
 
Keep up the amazing work on the mod, I love it to bits. :]

**Comment by absolutelyaya** [comment]
I'm not sure how much I can do about that yet- I'll have 2 experiment with it a bit

**Comment by V1E4S** [comment]
its alright, just informing you ^_^
