### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by Quickburst** [absolutelyaya/ultracraft#71]
I am unsure whether or not the issue stems from this mod or the other, however, they do not seem to launch with each other. I have already tested a game without one or the other and they seem to work individually with my pack. So something is definitely going on here.

Attached is a crash report.
[crash-2023-08-25_19.32.38-client.txt](https://github.com/absolutelyaya/ultracraft/files/12438323/crash-2023-08-25_19.32.38-client.txt)

Sorry if I got it wrong. Sick mod btw.

**Comment by absolutelyaya** [comment]
mainly saying this so I don't have 2 read through the log again later
The issue is `LivingEntityRenderMixin::adjustTickDelta`; It expects the 4th argument 2 be a float, which for some reason it isn't 
(in other words, yea the issue is on Ultracrafts side)

**Comment by absolutelyaya** [comment]
after thinking about it more, due to a lot of issues that would arise with the mods mechanics, I'm not planning on making the mods compatible
