### ISSUE TITLE
Shotgun swapping and terminal issues

### ISSUE THREAD

**Issue by Dreiasaiy** [absolutelyaya/ultracraft#80]
I can't seem to swap the shotgun variants when I press the swap button.

Also the terminal menu doesn't show properly with bsl shaders (and Im guessing most others, I just use bsl so I'm not too sure.)

**Comment by absolutelyaya** [comment]
For switching weapon variants you need to have obtained at least 2 variants of a weapon; you can do that by crafting them at the terminal or using `/ultracraft progression obtained grant <item-id>` (for example "ultracraft:pump_shotgun")

Shaders won't be fully supported. Best I can do is make the game not crash when using them unfortunately

**Comment by Dreiasaiy** [comment]
I have both variants equipped and gotten on the terminal. I'll try the command.
