### ISSUE TITLE
Using Terminal with pierce revolver in hand

### ISSUE THREAD

**Issue by ShadowZecro965** [absolutelyaya/ultracraft#83]
if you hold a pierce revolver in your hand it will crash when you use the terminal twice, i only did it with the revolver so it could be more weapons. the crash i get is "The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler"

**Comment by absolutelyaya** [comment]
do you have the full crashlog? you can find it at `<minecraft-directory>/crash-reports`

**Comment by ShadowZecro965** [comment]
i do have the full crash log and i recently discovered that it doesn't matter what i hold. i have no idea what happened to cause the crash anymore it just decided to happen

edit: after some testing with buttons it appears that only the weapons button causes a crash

[crash-2023-11-19_19.24.12-client.txt](https://github.com/absolutelyaya/ultracraft/files/13402996/crash-2023-11-19_19.24.12-client.txt)

**Comment by absolutelyaya** [comment]
fixed internally; do `/ultracraft progression unlocked grant @s ultracraft:pierce_revolver` as a temporary fix
