### ISSUE TITLE
Sky block is freaking out

### ISSUE THREAD

**Issue by GladiosAnimations** [absolutelyaya/ultracraft#87]
basically: i place skyblocks alongside eachother, and they starts freaking out, the parlax is only from one side, and when I turn, the side I'm turning to changes to day skyblock instead of moon.

my current mods: iris shaders (shaders turned off) and.. that's it.
also the upper skybox changes to the nearby texture (cerberus, hell spawner)

**Comment by absolutelyaya** [comment]
removing iris should fix it
rendering stuff like this won't ever be fully compatible with it unfortunately

**Comment by absolutelyaya** [comment]
nvmd, looks like other block entities with special renderers such as chests, signs and the examples you mentioned generally are actually the issue
Iris usually breaks stuff like this, so I hastily assumed it's that
