### ISSUE TITLE
Trying to use mods like construction wand do some weird things

### ISSUE THREAD

**Issue by Jasdernn** [absolutelyaya/ultracraft#88]
Pretty sure it's because all of the skybox blocks are labeled skybox, instead of them having different names, if that makes sense. Also, if this but is for construction wand, then it's for world edit too, which is a bigger problem
![2023-11-30_22 16 29_2](https://github.com/absolutelyaya/ultracraft/assets/148498785/26e2c932-be3b-4bb8-b975-eac0543fac91)

**Comment by absolutelyaya** [comment]
they're all the same block, but they have different nbt data; using worldedit, you'd fill an area with evening sky blocks using something like `//set ultracraft:sky_block{type:"evening"}` for example
