### ISSUE TITLE
Coining Crashing my game

### ISSUE THREAD

**Issue by Jacktastic09** [absolutelyaya/ultracraft#89]
Im unsure why it might be doing that, but here's the Crash Code:
[crash-2023-12-01_18.17.17-server.txt](https://github.com/absolutelyaya/ultracraft/files/13522227/crash-2023-12-01_18.17.17-server.txt)

**Comment by absolutelyaya** [comment]
duplicate of #85 and #86
Coins or Sharpshooter bounces cosidering Tameable entities without owners as a target cause the game to crash currently; it's fixed internally already tho
