### ISSUE TITLE
Game Crash from sharpshooter + Blade-machine twins

### ISSUE THREAD

**Issue by Jacktastic09** [absolutelyaya/ultracraft#91]
I was fighting the blade machine twins when upon using a fully charge sharp shooter shot on an almost dead (agony i think?) caused my game to crash with this error code:

The game crashed whilst ticking entity
displayed error: Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3213.method_5408(float)" because "this.bossBar" is null
copied button error: -1

**Comment by Jacktastic09** [comment]
extra notes: this was on the latest version, there were re-enforced glass panes + vent covers nearby and a really, REALLY tall elevator shaft with a terminal nearby

**Comment by absolutelyaya** [comment]
did the swordsmachine have a bossbar?

**Comment by Jacktastic09** [comment]
yes as they were agony and tundra spawned from the egg item. might've
tried to attack one of their swords or something
