### ISSUE TITLE
Console is not able to run the "ultrawhitelist graffiti/hivel add [player]" command

### ISSUE THREAD

**Issue by delishoes** [absolutelyaya/ultracraft#93]
I have tried whitelisting player through a command block, but it did not work, saying that "the command is unknown or incomplete". An operator can however do it without problems. I do not know if its intentional or not but it should probably be made that the console can execute this command too.

I have tried running it through the execute command too, but it still did not work.

**Comment by absolutelyaya** [comment]
yes, that was intentional, but I understand that there is an actual use-case for the command in command blocks or datapack functions. It'll be changed in the next update
