### ISSUE TITLE
Boats/Related items don't work in blood

### ISSUE THREAD

**Issue by Jasdernn** [absolutelyaya/ultracraft#95]
I just feel like if you were in a custom-made map, and you had to boat ride down a river of blood or do an Iron Lung with a AC Submarine it would be cool af. But yet again, liquids are pretty hard to mod in.
![2023-12-24_16 20 33](https://github.com/absolutelyaya/ultracraft/assets/148498785/47770845-9b77-423c-ad78-50fbc0a3579e)
(Also I get it if you don't wanna put fish in le blood but having a Hullbreaker chase you from an ocean of blood would be terrifying)

**Comment by absolutelyaya** [comment]
the boat should still work fine, the issue is purely visual. I'll look into that tho
