### ISSUE TITLE
Terminal is goofy

### ISSUE THREAD

**Issue by 1Grobotron1** [absolutelyaya/ultracraft#98]
![2023-12-29_17 34 59](https://github.com/absolutelyaya/ultracraft/assets/153846880/df6b3165-7317-467e-aea3-e28b29a23fd5)
No fix?

**Comment by absolutelyaya** [comment]
can't do much about your shaders breaking rendering stuff. I won't ever fully support use of shaders, best I can do is make them not crash the game
